-- ============================================
-- 添加个人日程进展更新功能
-- ============================================
-- 此脚本为 schedules 表添加进展跟踪功能
-- 包括完成率、进展更新历史等

-- 1. 为 schedules 表添加进展相关字段
ALTER TABLE schedules 
  ADD COLUMN IF NOT EXISTS progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  ADD COLUMN IF NOT EXISTS last_progress_update_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. 创建进展更新历史表
CREATE TABLE IF NOT EXISTS schedule_progress_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  progress INTEGER NOT NULL CHECK (progress >= 0 AND progress <= 100),
  update_content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 启用 RLS
ALTER TABLE schedule_progress_updates ENABLE ROW LEVEL SECURITY;

-- 4. 创建 RLS 策略
DROP POLICY IF EXISTS "Users can view their own progress updates" ON schedule_progress_updates;
DROP POLICY IF EXISTS "Users can insert their own progress updates" ON schedule_progress_updates;
DROP POLICY IF EXISTS "Users can update their own progress updates" ON schedule_progress_updates;
DROP POLICY IF EXISTS "Users can delete their own progress updates" ON schedule_progress_updates;

CREATE POLICY "Users can view their own progress updates" ON schedule_progress_updates
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own progress updates" ON schedule_progress_updates
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own progress updates" ON schedule_progress_updates
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own progress updates" ON schedule_progress_updates
  FOR DELETE USING (auth.uid() = user_id);

-- 5. 创建索引
CREATE INDEX IF NOT EXISTS idx_schedule_progress_updates_schedule_id ON schedule_progress_updates(schedule_id);
CREATE INDEX IF NOT EXISTS idx_schedule_progress_updates_user_id ON schedule_progress_updates(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_progress_updates_created_at ON schedule_progress_updates(created_at DESC);

-- 6. 创建触发器：自动更新 schedules 表的 last_progress_update_at 和 updated_at
CREATE OR REPLACE FUNCTION update_schedule_progress_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  -- 更新 schedules 表的 last_progress_update_at 和 updated_at
  UPDATE schedules
  SET 
    last_progress_update_at = NEW.created_at,
    updated_at = NEW.created_at,
    progress = NEW.progress
  WHERE id = NEW.schedule_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 删除现有触发器（如果存在）
DROP TRIGGER IF EXISTS trigger_update_schedule_progress_timestamp ON schedule_progress_updates;

-- 创建触发器
CREATE TRIGGER trigger_update_schedule_progress_timestamp
  AFTER INSERT ON schedule_progress_updates
  FOR EACH ROW
  EXECUTE FUNCTION update_schedule_progress_timestamp();

-- 7. 创建触发器：自动更新 schedules 表的 updated_at（当直接更新 schedules 表时）
CREATE OR REPLACE FUNCTION update_schedule_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 删除现有触发器（如果存在）
DROP TRIGGER IF EXISTS trigger_update_schedule_updated_at ON schedules;

-- 创建触发器
CREATE TRIGGER trigger_update_schedule_updated_at
  BEFORE UPDATE ON schedules
  FOR EACH ROW
  EXECUTE FUNCTION update_schedule_updated_at();

-- 8. 验证
SELECT 
  '进展更新功能添加成功！' AS message,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'schedules' AND column_name IN ('progress', 'last_progress_update_at', 'updated_at')) AS schedule_columns_added,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'schedule_progress_updates') AS progress_table_created;
