-- ============================================
-- 创建个人日程管理表 (schedules)
-- ============================================
-- 此脚本用于创建个人日程管理功能所需的 schedules 表
-- 如果表已存在，可以使用 DROP TABLE 先删除，或使用 CREATE TABLE IF NOT EXISTS

-- 创建 schedules 表（包含状态字段）
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建 RLS (Row Level Security) 策略
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- 删除现有策略（如果存在），避免重复创建错误
DROP POLICY IF EXISTS "Users can view their own schedules" ON schedules;
DROP POLICY IF EXISTS "Users can insert their own schedules" ON schedules;
DROP POLICY IF EXISTS "Users can update their own schedules" ON schedules;
DROP POLICY IF EXISTS "Users can delete their own schedules" ON schedules;

-- 用户只能访问自己的日程
CREATE POLICY "Users can view their own schedules" ON schedules
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own schedules" ON schedules
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own schedules" ON schedules
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own schedules" ON schedules
  FOR DELETE USING (auth.uid() = user_id);

-- 添加索引优化性能
CREATE INDEX IF NOT EXISTS idx_schedules_user_id ON schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date_time ON schedules(date, time);
CREATE INDEX IF NOT EXISTS idx_schedules_status ON schedules(status);

-- 添加状态约束（如果不存在）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'check_status'
  ) THEN
    ALTER TABLE schedules ADD CONSTRAINT check_status
      CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'));
  END IF;
END $$;

-- 验证表创建成功
SELECT 
  'schedules 表创建成功！' AS message,
  COUNT(*) AS column_count
FROM information_schema.columns 
WHERE table_name = 'schedules' AND table_schema = 'public';
