-- ============================================
-- 团队任务过程性成果记录功能
-- ============================================
-- 功能说明：
-- 1. 记录任务执行过程中的事件（如例会、活动等）
-- 2. 支持上传照片、会议纪要、成果文件等
-- 3. 关联到具体的任务（task_id）或工作子项（work_item_id）
-- ============================================

-- 1. 创建任务事件表
CREATE TABLE IF NOT EXISTS task_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  event_type VARCHAR(50) NOT NULL CHECK (event_type IN ('meeting', 'activity', 'milestone', 'other')),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  location VARCHAR(255),
  participants TEXT, -- JSON数组，存储参与者user_id
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 创建事件文件表
CREATE TABLE IF NOT EXISTS task_event_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES task_events(id) ON DELETE CASCADE,
  file_type VARCHAR(50) NOT NULL CHECK (file_type IN ('photo', 'document', 'meeting_minutes', 'result_file', 'other')),
  file_name VARCHAR(255) NOT NULL,
  file_path TEXT NOT NULL, -- Supabase Storage路径
  file_size BIGINT, -- 文件大小（字节）
  mime_type VARCHAR(100), -- MIME类型
  uploaded_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 创建索引
CREATE INDEX IF NOT EXISTS idx_task_events_task_id ON task_events(task_id);
CREATE INDEX IF NOT EXISTS idx_task_events_work_item_id ON task_events(work_item_id);
CREATE INDEX IF NOT EXISTS idx_task_events_event_date ON task_events(event_date DESC);
CREATE INDEX IF NOT EXISTS idx_task_events_created_by ON task_events(created_by);
CREATE INDEX IF NOT EXISTS idx_task_event_files_event_id ON task_event_files(event_id);
CREATE INDEX IF NOT EXISTS idx_task_event_files_file_type ON task_event_files(file_type);

-- 4. 启用 RLS
ALTER TABLE task_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_event_files ENABLE ROW LEVEL SECURITY;

-- 5. 删除现有策略（如果存在）
DROP POLICY IF EXISTS "Team members can view task events" ON task_events;
DROP POLICY IF EXISTS "Team members can create task events" ON task_events;
DROP POLICY IF EXISTS "Team members can update task events" ON task_events;
DROP POLICY IF EXISTS "Team members can delete task events" ON task_events;

DROP POLICY IF EXISTS "Team members can view event files" ON task_event_files;
DROP POLICY IF EXISTS "Team members can upload event files" ON task_event_files;
DROP POLICY IF EXISTS "Team members can delete event files" ON task_event_files;

-- 6. 创建 RLS 策略 - task_events
-- 查看：团队成员可以查看所属团队的任务事件
CREATE POLICY "Team members can view task events" ON task_events
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_events.task_id
      AND tm.user_id = auth.uid()
    )
  );

-- 创建：团队成员可以创建事件
CREATE POLICY "Team members can create task events" ON task_events
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_events.task_id
      AND tm.user_id = auth.uid()
    )
    AND created_by = auth.uid()
  );

-- 更新：创建者或团队管理员可以更新
CREATE POLICY "Team members can update task events" ON task_events
  FOR UPDATE
  USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_events.task_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('owner', 'admin')
    )
  )
  WITH CHECK (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_events.task_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('owner', 'admin')
    )
  );

-- 删除：创建者或团队管理员可以删除
CREATE POLICY "Team members can delete task events" ON task_events
  FOR DELETE
  USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_events.task_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('owner', 'admin')
    )
  );

-- 7. 创建 RLS 策略 - task_event_files
-- 查看：团队成员可以查看事件文件
CREATE POLICY "Team members can view event files" ON task_event_files
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM task_events te
      JOIN tasks t ON t.id = te.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE te.id = task_event_files.event_id
      AND tm.user_id = auth.uid()
    )
  );

-- 上传：团队成员可以上传文件
CREATE POLICY "Team members can upload event files" ON task_event_files
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM task_events te
      JOIN tasks t ON t.id = te.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE te.id = task_event_files.event_id
      AND tm.user_id = auth.uid()
    )
    AND uploaded_by = auth.uid()
  );

-- 删除：上传者或团队管理员可以删除
CREATE POLICY "Team members can delete event files" ON task_event_files
  FOR DELETE
  USING (
    uploaded_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM task_events te
      JOIN tasks t ON t.id = te.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE te.id = task_event_files.event_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('owner', 'admin')
    )
  );

-- 8. 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_task_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_task_events_updated_at ON task_events;
CREATE TRIGGER trigger_update_task_events_updated_at
  BEFORE UPDATE ON task_events
  FOR EACH ROW
  EXECUTE FUNCTION update_task_events_updated_at();

-- 9. 创建 Supabase Storage Bucket（需要在 Supabase Dashboard 中手动创建）
-- Storage Bucket 名称：task-event-files
-- Public: false（私有存储）
-- File size limit: 10MB（可根据需要调整）
-- Allowed MIME types: image/*, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

-- 10. Storage Bucket 策略（需要在 Supabase Dashboard > Storage > Policies 中配置）
-- 策略名称：Team members can upload files
-- 策略类型：INSERT
-- 策略定义：
-- (bucket_id = 'task-event-files'::text) AND (
--   EXISTS (
--     SELECT 1 FROM task_events te
--     JOIN tasks t ON t.id = te.task_id
--     JOIN team_members tm ON tm.team_id = t.team_id
--     WHERE (storage.foldername(name))[1] = te.id::text
--     AND tm.user_id = auth.uid()
--   )
-- )

-- 策略名称：Team members can view files
-- 策略类型：SELECT
-- 策略定义：
-- (bucket_id = 'task-event-files'::text) AND (
--   EXISTS (
--     SELECT 1 FROM task_events te
--     JOIN tasks t ON t.id = te.task_id
--     JOIN team_members tm ON tm.team_id = t.team_id
--     WHERE (storage.foldername(name))[1] = te.id::text
--     AND tm.user_id = auth.uid()
--   )
-- )

-- 策略名称：Team members can delete files
-- 策略类型：DELETE
-- 策略定义：
-- (bucket_id = 'task-event-files'::text) AND (
--   owner = auth.uid()
--   OR EXISTS (
--     SELECT 1 FROM task_events te
--     JOIN tasks t ON t.id = te.task_id
--     JOIN team_members tm ON tm.team_id = t.team_id
--     WHERE (storage.foldername(name))[1] = te.id::text
--     AND tm.user_id = auth.uid()
--     AND tm.role IN ('owner', 'admin')
--   )
-- )
-- 
-- ⚠️ 重要提示：
-- 1. Storage Policies 中直接使用 name（不是 objects.name）
-- 2. storage.foldername(name) 是正确的语法
-- 3. 确保选择 DELETE 操作类型（不是 SELECT）

-- ============================================
-- 完成
-- ============================================
-- 执行此脚本后，请：
-- 1. 在 Supabase Dashboard > Storage 中创建 bucket: task-event-files
-- 2. 配置 Storage Policies（见上面的注释）
-- 3. 验证表结构和 RLS 策略是否正确创建
-- ============================================
