-- ==========================================
-- 团队项目管理系统 - 团队版全量数据库配置
-- ==========================================

-- 1. 核心表结构创建

-- 团队表
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 团队成员表
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role VARCHAR(50) DEFAULT 'member', -- owner, admin, member
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(team_id, user_id)
);

-- 工作组表
CREATE TABLE IF NOT EXISTS work_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  leader_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作组成员表
CREATE TABLE IF NOT EXISTS work_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(work_group_id, user_id)
);

-- 任务表
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  status VARCHAR(20) DEFAULT 'pending', -- pending, in_progress, completed, cancelled
  priority VARCHAR(20) DEFAULT 'medium', -- low, medium, high
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作子项表
CREATE TABLE IF NOT EXISTS work_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  execution_order VARCHAR(20) NOT NULL, -- parallel, sequential
  sequence_number INTEGER DEFAULT 0, -- 顺序号
  planned_start_time TIMESTAMP WITH TIME ZONE,
  duration_hours DECIMAL(5,2), -- 预计时长
  planned_end_time TIMESTAMP WITH TIME ZONE,
  assignee_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  collaborators JSONB DEFAULT '[]'::jsonb, -- 配合人列表
  objectives TEXT, -- 工作目标
  status VARCHAR(20) DEFAULT 'pending', -- pending, in_progress, completed, cancelled, blocked
  progress INTEGER DEFAULT 0, -- 0-100
  actual_start_time TIMESTAMP WITH TIME ZONE,
  actual_end_time TIMESTAMP WITH TIME ZONE,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作子项状态历史表
CREATE TABLE IF NOT EXISTS work_item_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL,
  progress INTEGER DEFAULT 0,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 任务/子项评论表
CREATE TABLE IF NOT EXISTS task_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 索引优化

CREATE INDEX IF NOT EXISTS idx_teams_owner ON teams(owner_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_work_groups_team ON work_groups(team_id);
CREATE INDEX IF NOT EXISTS idx_tasks_team ON tasks(team_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_work_items_task ON work_items(task_id);
CREATE INDEX IF NOT EXISTS idx_work_items_assignee ON work_items(assignee_id);

-- 3. 数据完整性约束 (CHECK Constraints)

ALTER TABLE team_members DROP CONSTRAINT IF EXISTS valid_member_role;
ALTER TABLE team_members ADD CONSTRAINT valid_member_role CHECK (role IN ('owner', 'admin', 'member'));

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS valid_task_status;
ALTER TABLE tasks ADD CONSTRAINT valid_task_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'));

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS valid_task_priority;
ALTER TABLE tasks ADD CONSTRAINT valid_task_priority CHECK (priority IN ('low', 'medium', 'high'));

ALTER TABLE work_items DROP CONSTRAINT IF EXISTS valid_work_item_status;
ALTER TABLE work_items ADD CONSTRAINT valid_work_item_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled', 'blocked'));

-- 4. 触发器 (updated_at 自动更新)

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;
CREATE TRIGGER update_tasks_updated_at 
BEFORE UPDATE ON tasks 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_work_items_updated_at ON work_items;
CREATE TRIGGER update_work_items_updated_at 
BEFORE UPDATE ON work_items 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 5. RLS (行级安全策略) 配置

ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_items ENABLE ROW LEVEL SECURITY;

-- 策略示例：团队成员可以查看其团队
DROP POLICY IF EXISTS "Team members can view their team" ON teams;
CREATE POLICY "Team members can view their team" ON teams
  FOR SELECT USING (
    id IN (SELECT team_id FROM team_members WHERE user_id = auth.uid())
    OR owner_id = auth.uid()
  );

-- 策略示例：只有负责人或团队管理员可以更新任务
DROP POLICY IF EXISTS "Team members can view tasks" ON tasks;
CREATE POLICY "Team members can view tasks" ON tasks
  FOR SELECT USING (
    team_id IN (SELECT team_id FROM team_members WHERE user_id = auth.uid())
  );
