-- ============================================
-- 更新个人日程表结构：日期范围 + 子项目
-- ============================================
-- 此脚本将 schedules 表的 date/time 改为 start_date/end_date
-- 并添加子项目功能

-- 1. 添加新字段（如果不存在）
ALTER TABLE schedules 
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS end_date DATE;

-- 2. 迁移现有数据（如果有 date 字段的数据）
DO $$
BEGIN
  -- 如果存在 date 字段，将 date 的值迁移到 start_date
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'schedules' AND column_name = 'date'
  ) THEN
    UPDATE schedules 
    SET start_date = date 
    WHERE start_date IS NULL AND date IS NOT NULL;
    
    -- 如果没有 end_date，将 start_date 复制到 end_date
    UPDATE schedules 
    SET end_date = start_date 
    WHERE end_date IS NULL AND start_date IS NOT NULL;
  END IF;
END $$;

-- 3. 创建子项目表
CREATE TABLE IF NOT EXISTS schedule_sub_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 启用 RLS
ALTER TABLE schedule_sub_items ENABLE ROW LEVEL SECURITY;

-- 5. 创建 RLS 策略
DROP POLICY IF EXISTS "Users can view their own sub items" ON schedule_sub_items;
DROP POLICY IF EXISTS "Users can insert their own sub items" ON schedule_sub_items;
DROP POLICY IF EXISTS "Users can update their own sub items" ON schedule_sub_items;
DROP POLICY IF EXISTS "Users can delete their own sub items" ON schedule_sub_items;

CREATE POLICY "Users can view their own sub items" ON schedule_sub_items
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own sub items" ON schedule_sub_items
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own sub items" ON schedule_sub_items
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own sub items" ON schedule_sub_items
  FOR DELETE USING (auth.uid() = user_id);

-- 6. 创建索引
CREATE INDEX IF NOT EXISTS idx_schedule_sub_items_schedule_id ON schedule_sub_items(schedule_id);
CREATE INDEX IF NOT EXISTS idx_schedule_sub_items_user_id ON schedule_sub_items(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_sub_items_order_index ON schedule_sub_items(order_index);

-- 7. 创建触发器：自动更新 updated_at
CREATE OR REPLACE FUNCTION update_schedule_sub_item_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_schedule_sub_item_updated_at ON schedule_sub_items;

CREATE TRIGGER trigger_update_schedule_sub_item_updated_at
  BEFORE UPDATE ON schedule_sub_items
  FOR EACH ROW
  EXECUTE FUNCTION update_schedule_sub_item_updated_at();

-- 8. 更新 schedules 表的索引（移除旧的 date/time 索引，添加新的）
DROP INDEX IF EXISTS idx_schedules_date_time;
CREATE INDEX IF NOT EXISTS idx_schedules_start_date ON schedules(start_date);
CREATE INDEX IF NOT EXISTS idx_schedules_end_date ON schedules(end_date);
CREATE INDEX IF NOT EXISTS idx_schedules_date_range ON schedules(start_date, end_date);

-- 9. 添加日期范围约束（确保 end_date >= start_date）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'check_date_range'
  ) THEN
    ALTER TABLE schedules ADD CONSTRAINT check_date_range
      CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date);
  END IF;
END $$;

-- 10. 验证
SELECT 
  '日期结构更新成功！' AS message,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'schedules' AND column_name IN ('start_date', 'end_date')) AS date_columns_added,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'schedule_sub_items') AS sub_items_table_created;

-- 注意：time 字段保留但不使用，date 字段也保留以兼容旧数据
-- 如果需要完全移除，可以执行：
-- ALTER TABLE schedules DROP COLUMN IF EXISTS time;
-- ALTER TABLE schedules DROP COLUMN IF EXISTS date;
